moviegraph/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scores.urls')),
]

scores/urls.py
from django.urls import path

from . import views

app_name = 'scores'

urlpatterns = [
    path('', views.index, name='root'),
    path('index', views.index, name='index'),
    path('validate', views.validate, name='validate'),
    path('actors', views.actors, name='actors'),
    path('search', views.search, name='search'),
    # path('search_json', views.search_json, name='search_json')
]

scores/models.py
"""
Set up models based on structure of IMDB data.

Modified Title and Name models by adding join tables for
TitleGenre and NameProfession to avoid storing arrays in
a single data field.

This will also simplify adding features in the future
(only search for actors, or exclude all tv shows, etc.).
"""

from django.db import models


# Create your models here.
class Title(models.Model):
    """Define title (movie, TV show, etc.) model."""

    id = models.CharField(max_length=9, primary_key=True)
    title_type = models.CharField(max_length=50)
    primary_title = models.TextField(null=True)
    is_adult = models.BooleanField()
    start_year = models.IntegerField(null=True)
    end_year = models.IntegerField(null=True)
    genres = models.TextField(null=True)

    def __str__(self):
        """Return string representation of Title."""
        return self.primary_title + ', ' + str(self.start_year)


class Name(models.Model):
    """Define name model."""

    id = models.CharField(max_length=9, primary_key=True)
    primary_name = models.CharField(max_length=200)
    lowercase_name = models.CharField(
        db_index=True,
        max_length=200,
        default=''
    )
    birth_year = models.PositiveSmallIntegerField(null=True)
    death_year = models.PositiveSmallIntegerField(null=True)
    professions = models.TextField(null=True)
    known_for = models.TextField(null=True)
    in_graph = models.BooleanField(default=False)

    def __str__(self):
        """Return string representation of Name."""
        return self.primary_name


class Principal(models.Model):
    """
    Join table for Name and Title.

    All the principal cast for a given title.
    """

    title = models.ForeignKey(Title, on_delete=models.CASCADE)
    name = models.ForeignKey(Name, on_delete=models.CASCADE)

    def __str__(self):
        """Return string representation of Principal."""
        s = str(self.name) + " in title: " + str(self.title)

        return s


class Graph(models.Model):
    """
    Table that contains graph info.

    Name, Costar, and all titles they have in common.
    """

    id = models.IntegerField(primary_key=True)
    star = models.ForeignKey(
        Name,
        on_delete=models.CASCADE,
        related_name='star'
    )
    costar = models.ForeignKey(
        Name,
        on_delete=models.CASCADE,
        related_name='costar'
    )
    titles = models.TextField()

scores/views.py
"""Index and search views (and their helper functions)."""

from django.shortcuts import render
from django.http import JsonResponse

from .graph import search_graph2, KEVIN_BACON_ID
from .images import get_actor_image, get_movie_image
from .models import Name
from django.db.models import Q


def get_actor(name):
    """
    Check whether a given name is in the graph table.

    Returns actor if found; else None.
    """
    name = name.lower()

    if name == 'kevin bacon':
        return Name.objects.get(id=KEVIN_BACON_ID)

    results = Name.objects.filter(
        Q(lowercase_name=name) &
        Q(in_graph=True)
    )
    try:
        actor = results[0]
        return actor
    except IndexError:
        return None


def get_images(path):
    """
    Get actor and movie images for the nodes and edges in the path.

    Takes in a list of tuples (actor, movie) and returns a list of
    dictionaries with actor and movies as the keys, and tuples (or
    a list of tuples for movies) of the form (actor/movie, image) as
    the values.
    """
    path_with_images = []

    for step in path:
        actor = step[0]
        movies = step[1]

        actor_info = (actor, get_actor_image(actor.primary_name))
        movies_info = [
            (movie, get_movie_image(movie.primary_title))
            for movie in movies
        ]

        path_with_images.append({'actor': actor_info, 'movies': movies_info})

    return path_with_images


def get_info(path):
    """
    Get actor and movie info for rendering as json.

    Takes in list of tuples (actor, movie) and returns a list of
    dictionaries with actor and movies as the keys, and tuples (or
    list of tuples for movies) of the form (actor/movie name, movie
    year, image) as the values.
    """
    path_with_images = []

    for step in path:
        actor = step[0]
        movies = step[1]

        actor_info = (
            actor.id,
            actor.primary_name,
            get_actor_image(actor.primary_name))
        movies_info = [
            (
                movie.id,
                movie.primary_title,
                movie.start_year,
                get_movie_image(movie.primary_title)
            )
            for movie in movies
        ]

        path_with_images.append({'actor': actor_info, 'movies': movies_info})

    return path_with_images


def index(request):
    """View function for main/home page."""
    return render(request, 'scores/index.html')


def validate(request):
    """
    Validate actor name exists in database before searching.

    If more than one name fits the criteria, selects the first one
    and returns the id.

    Won't render.
    """
    search_for = request.GET.get('search-for', default='')
    start_from = request.GET.get('start-from', default='')

    data = {}

    search_for_actor = get_actor(search_for)
    start_from_actor = get_actor(start_from)

    if not search_for_actor:
        data['errors'] = {'search-for': 'Not a valid name'}
    if not start_from_actor:
        data['errors'] = {'start-from': 'Not a valid name'}

    if 'errors' in data:
        data['status'] = 'false'
        return JsonResponse(data, status=404)
    else:
        data = {
            'search-for': search_for_actor.id,
            'start-from': start_from_actor.id,
        }
        return JsonResponse(data)


def search(request):
    """Search graph table using BFS to find Bacon score."""
    search_for = request.GET.get('search-for', default='')
    start_from = request.GET.get('start-from', default='')

    print(search_for)
    print(start_from)

    data = {}

    path = search_graph2(search_for, start_from)
    print(path)

    path_with_images = get_info(path)
    data['path'] = path_with_images

    name = Name.objects.get(id=search_for).primary_name
    data['path_end'] = (
        search_for,
        name,
        get_actor_image(name)
    )

    return JsonResponse(data)


def actors(request):
    """
    Return list of actors for datalist in app.js.

    View isn't rendered; only used to return json to app.js.
    """
    search_for = request.GET.get('name', default='').lower()
    LIMIT = 20

    actor_list = []
    actors = Name.objects.filter(
        Q(lowercase_name__startswith=search_for) &
        Q(birth_year__isnull=False) &
        (Q(professions__icontains='actor') |
         Q(professions__icontains='actress'))
    )[:LIMIT]

    # keep track of count to see whether to keep
    # making calls to /actors in app.js
    complete = False
    count = 0
    for actor in actors:
        actor_list.append({
            'actor_id': actor.id,
            'actor_name': actor.primary_name
        })
        count += 1

    if count < LIMIT:
        complete = True

    return JsonResponse({'actors': actor_list, 'complete': complete})

scores/templates/scores/index.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8">
    <title>MovieGraph</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" integrity="sha256-GSio8qamaXapM8Fq9JYdGNTvk/dgs+cMLgPeevOYEx0=" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Jura|Orbitron" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'scores/style.css' %}" />
    <link rel="icon" href="{% static 'scores/images/favicon.ico' %}" />
  </head>

  <body class="init grid-x grid-padding-x align-middle">

    <header class="small-12 cell header" hidden=true>
      <a href="{% url 'scores:root' %}"><h1>Movie + Graph</h1></a>
    </header>
    <main class="small-12 cell grid-x align-center">

      <form class="grid-x grid-margin-x small-10 large-8 cell" action="{% url 'scores:search' %}" method="get" id="search-graph-form">
        <div class="grid-y small-12 cell input-wrapper">
          <input type="search" name="start-from" value="{{ start_from|default:'Kevin Bacon' }}" id="start-from" list="actor-list1" class="small-12 cell" required/>
          <datalist id="actor-list1"></datalist>
          <span class="error both small-12 cell">
            <p class="error start-from"></p>
            <p class="error both"></p>
          </span>
        </div>

        <div class="grid-y small-12 cell input-wrapper">
          <input type="search" name="search-for" id="search-for" list="actor-list2" placeholder="Name" value="{{ search_for }}" class="small-12 cell" required/>
          <datalist id="actor-list2"></datalist>
          <span class="error small-12 cell">
            <p class="error search-for"></p>
          </span>
        </div>

        <div class="grid-y small-12 cell button-wrapper">
          <button type="submit" class="button small-12 cell home" id="search-graph">Search</button>
        </div>
      </form>

      <!-- <div class="loader-wrapper grid-x"> -->
        <div class="loader small-6 large-4 cell" hidden=true></div>
      <!-- </div> -->

      <section class="path grid-x small-12 cell align-center">

        <h3 class="small-12 cell score">
        </h3>
        <ul class="actors grid-x small-12 cell align-center"></ul>
      </section>
    </main>

      <footer class="small-12 cell align-justify align-middle" hidden=true>
        <section class="imdb-attribution grid-x small-4 cell align-bottom">
          <span class="imdb-attribution">
            <p>Data and links from</p>
          </span>
            <div class="logo-container grid-x small-2 cell">
              <a href="http://www.imdb.com/" target="_blank">
                <img src="{% static 'scores/images/imdb_logo.png' %}" alt="IMDb logo" />
              </a>
            </div>
        </section>

        <small class="small-4 cell">&copy; <a href="https://github.com/IsabelDePapel" target="_blank">Isabel Suchanek, 2018</a></small>

        <section class="tmdb-attribution grid-x small-4 cell align-middle align-right">
          <span class="tmdb-attribution">
            <p>Images courtesy of</p>
          </span>
          <div class="logo-container grid-x small-2 cell">
            <a href="https://www.themoviedb.org" target="_blank">
              <img src="{% static 'scores/images/tmdb_logo.png' %}" alt="TMDb logo" />
            </a>
          </div>
        </section>
      </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <script src="{% static 'scores/app.js' %}" type="text/javascript"></script>

  </body>
</html>